imports:
    - { resource: services.yml }

parameters:
    locale: en
    secret: asdqwe123

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/Configuration/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      ~
    templating:
        engines: ['php']
    default_locale:  "%locale%"
    session:
        handler_id:  session.handler.native_file
    http_method_override: true
    php_errors:
        log: true
